### ISSUE TITLE
[Feedback]: navigation 文档描述不太对

### ISSUE THREAD

**Issue by FireTable** [blocklet/blocklet-site#101]
[Enter feedback here]

1. 缺少了想隐藏某个子组件的描述 `visible`, 比如: NFT Maker 想把 NFT Store 的挂载菜单隐藏了
```
 - id: store
    title:
      en: NFT Store
      zh: NFT Store
    component: nft-store
    visible: false

```
2. components => component?
<img width="551" alt="image" src="https://user-images.githubusercontent.com/24667209/211733329-99aedca2-8e72-4b5e-a5a7-8663dbfe6574.png">

---
#### Document Details
* AppId: zNKh7m9JccKmZY8vCSbkdYVoXem5CceAiYD1
* Content: [blocklet.yml](https://developer.blocklet.io/docs/zh/reference/blocklet-spec#navigation)
* Content Source: [developer/docs/pages/reference/blocklet-spec/index.zh.md](https://github.com/blocklet/blocklet-site/tree/main/developer/docs/pages/reference/blocklet-spec/index.zh.md)
* Version: 0.1.119
