### ISSUE TITLE
[DOC] 付费子组件声明文档

### ISSUE THREAD

**Issue by linchen1987** [blocklet/blocklet-site#20]
```yml
payment
	componentPrice
		- type: percentage # fixed, percentage
		  value: 20%
		- parentPriceRange:
		   - 10
		   - 20
          type: fixed # fixed, percentage
		  value: 2

payment
	componentPrice
       type: percentage # fixed, percentage
	   value: 0.1
```
